/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 scene.gltf
Author: Alexandre Tokovinine (https://sketchfab.com/tokovinin3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/harvard-yenching-institute-statue-fc245710c4d64d0886a7f37dc522ff87
Title: Harvard-Yenching Institute statue
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[5.43, 5.53, -0.02]} rotation={[1.43, -1.54, 2.99]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.material_2} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
